---
exclude_paths:
  - "Dockerfile"
  - "docs/javascripts/**"
  - "docs/docs/**"
  - "docs/source/conf.py"
  - "experiment/widget/pkgs_AdaFair.py"
  - "experiment/widget/pkgs_AdaFair_py36.py"

# engines:
#   pylint:
#     python_version: 2
#
# engines:
#   metric:
#     exclude_paths:
#       - "experiment/wp2_oracle/**"
#     # config:
#     #   languages:
#     #     - "python"