# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-python/ for more details
#
version: 2.1

# Aliases to reuse
_defaults: &defaults
  docker:
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/developer/images/image/cimg/python
    - image: cimg/python:3.11.8
  working_directory: ~/project


jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            pip install --upgrade setuptools pip
            pip install -r requirements.txt
            pip install carbontracker pytest
            pip install coverage coveralls pytest-xdist
            coverage run -m pytest --ignore-glob="*/excl_test_*,*/pkgs*"
            coverage report
            coverage html
            # rm *.png && rm *.csv && rm *.log
            coverage xml
            export COVERALLS_REPO_TOKEN=t6J3mEIT6dA8Kb1YBd4ssBp2bao0cxgzM
            export CODACY_PROJECT_TOKEN=082ca48f7f2e46649be75c2a495cfc66
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
            # bash <(curl -Ls https://coverage.codacy.com/get.sh)
            # python -m pytest fairml/facils/excl_test*
            # rm chart*.pdf && rm cheers*.pdf && rm fairgbm*.pdf

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  version: 2
  default:
    jobs:
      - build-and-test
