# site_name: My Docs
# https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/

site_name: FairML documentation
site_url: https://fairml.readthedocs.io/en/latest/
site_author: Yijun Bian

# Repository
repo_name: eustomaqua/FairML
# repo_url: https://github.com/eustomaqua/FairML

# Copyright
copyright: Copyright &copy; 2025 Yijun

theme:
  # name: readthedocs
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      # scheme: default
      # primary: indigo # teal, light blue
      # accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Poppins Medium  # Georgia, Poppins, Roboto, Verdana
    code: Roboto Mono
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.tabs
    # - header.autohide
  # logo: ../docs/logo.svg  # material/library, assets/logo.png
  # logo: ../docs/github-brands-solid.svg  # pagelines-brands-solid.svg
  logo: pagelines-brands-solid.svg
  # icon:
  #   repo: fontawesome/brands/git-alt
  #   # site: fontawesome/brands/github
  # highlightjs: true
  # include_homepage_in_sidebar: True
  # prev_next_bottons_location: both
  # navigation_depth: 4
  # collapse_navigation: True
  # titles_only: False
  # sticky_navigation: True
  # locale: en
#   hljs_languages:
#     - yaml
#     - rust
#   analytics:
#     gtag: G-ABC123


plugins:
  - search
  - offline

nav:
  - Project description: index.md
  - Getting started: getting-started.md
  - General APIs: general-api.md
  - Documentation: ml-document.md
#   - Document
#   - About
