# site_name: My Docs
# https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/

site_name: FairML documentation
site_url: https://fairml.readthedocs.io/en/latest/
site_author: Yijun Bian

# Repository
repo_name: eustomaqua/FairML
# repo_url: https://github.com/eustomaqua/FairML

# Copyright
copyright: Copyright &copy; 2025 Yijun

theme:
  # name: readthedocs
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      # scheme: default
      # primary: indigo  # teal, light blue
      # accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal  # indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        # icon: material/eye  # weather-sunny, brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        # icon: material/eye-outline  # weather-night, brightness-4
        name: Switch to system preference
  font:
    text: Helvetica  # Georgia, Poppins Medium, Roboto, Verdana
    code: Arial  # Poppins, Roboto Mono, Helvetica
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.tabs
    # - header.autohide
    - content.code.copy
  # logo: ../docs/logo.svg  # material/library, assets/logo.png
  # logo: ../docs/github-brands-solid.svg  # pagelines-brands-solid.svg
  logo: pagelines-brands-solid.svg
  # icon:
  #   repo: fontawesome/brands/git-alt
  #   # site: fontawesome/brands/github
  # highlightjs: true
  # include_homepage_in_sidebar: True
  # prev_next_bottons_location: both
  # navigation_depth: 4
  # collapse_navigation: True
  # titles_only: False
  # sticky_navigation: True
  # locale: en
#   hljs_languages:
#     - yaml
#     - rust
#   analytics:
#     gtag: G-ABC123

extra_javascript:
  - 'javascripts/mathjax.js'
  - 'javascripts/MathJax_sing_file_main.js'
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - 'javascripts/MathJax-2.7.5/MathJax.js'
  # - 'javascripts/MathJax-2.7.5/extensions/MathMenu.js'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # - pymdownx.arithmatex:
  #   generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # - codehilite(linenums=true)    # 显示行号
  # - codehilite(guess_lang=true)  # 开启猜测，若不指定语言则自动高亮


plugins:
  - search
  - offline

nav:
  - Project description: index.md
  - Requirements: getting-started.md  # Getting started
  - WP1&2 examples: wp2-oracle.md
  - WP3 examples: wp3-causal.md
#   - General APIs: general-api.md    # API Docs
#   - Documentation: ml-document.md
#   - Document
#   - About
